### ISSUE TITLE
sentry won't store the remember_me token in DB

### ISSUE THREAD

**Issue by huglester** [cartalyst/sentry#480]
Hello everyone,

I have some tricky problem, I use sentry in CI install, everything works, but the remember_me

When I login with valid credentials, I get:

```
Cartalyst\Sentry\Users\UserNotFoundException [ 0 ]: A user was not found with the given credentials.
```

but the credentials are valid, if I not check the remember_me token - I pass this problem

I narrowed down to the query, where it searches for a user:

```php

select * from `default_sentry_users` where `email` = ? and `remember_me` = ? limit 1

bindings are:
my@email.com
accept
```

sure it won't find me, because this `remember_me` field is NULL on every user, noone jas remember me yet..

do you have any ides?

Thanks!

**Comment by brunogaspar** [comment]
The remember me token is stored on the cookie not on the database.
