### ISSUE TITLE
getLogin() doesn't work when working with a belongsTo relationship.

### ISSUE THREAD

**Issue by sniper7kills** [cartalyst/sentry#483]
Post Model:

    public function writer()
	{
	    return $this->belongsTo('\Cartalyst\Sentry\Users\Eloquent\User','writer_id');
    }
  	public function updater()
   	{
   		return $this->belongsTo('\Cartalyst\Sentry\Users\Eloquent\User','updater_id');
   	}

My issue is in my view I'm going through a set of posts and need to get the user login like so

    $post->writer->getLogin()

But it defaults to email. I'm assuming the service provider isn't being invoked and setting that value.

My question really just boils down to, what is the best way for me to invoke the service provider to set that in the package I am creating?

Thank you in advance.

**Comment by brunogaspar** [comment]
Sorry for the late reply, @sniper7kills are you still having this issue?

**Comment by sniper7kills** [comment]
Honestly, I don't know. I had put the project aside but I'll test it again tonight and I'll let you know.

**Comment by brunogaspar** [comment]
All right, if you still face the same issue let me know, i'll see if i can get some time to look into it.

**Comment by sniper7kills** [comment]
My apologies. I had forgotten about this completely. I did just check and it is still having the same issue.

**Comment by brunogaspar** [comment]
@sniper7kills I believe your issue is because of this https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/SentryServiceProvider.php#L106-L119 therefore you'll probably need to manually set the login attribute on the model on your application.

Something along these lines (not tested)

```php
$config = Config::get('cartalyst/sentry::users');

$model = app($config['model'])->setLoginAttributeName($config['login_attribute']);
```

**Comment by sniper7kills** [comment]
Amazing! That was exactly what I was looking for.
