### ISSUE TITLE
Why sentry don't use laravel's "remember me" strategy?

### ISSUE THREAD

**Issue by argb** [cartalyst/sentry#499]
laravel there is a remember_token,but sentry there is no this field,why ? I think laravel's strategy is better,could sentry support it to work together with laravel better?

**Comment by StarpTech** [comment]
+1

**Comment by brunogaspar** [comment]
It could, but Sentry is feature freeze now.

This feature is included on our premium Sentinel package.

**Comment by StarpTech** [comment]
It's an improvement not a feature.

**Comment by brunogaspar** [comment]
@StarpTech Sorry to disagree with you, but it's a feature.

You'll need to create a new migration to add a new field to the database, do the necessary code changes to make it work, add tests and bump the `minor`.

If it was an improvement, you would only bump the `patch`, as to me, improvements are to make the code more faster, readable, cleaner.. not to implement any new functionality.

Has a said, Sentry is feature freeze, therefore no new features will be implemented at this time.
