### ISSUE TITLE
Maximum Nesting Error from Sentry::createUser()

### ISSUE THREAD

**Issue by jamoy** [cartalyst/sentry#501]
I am getting a nesting error from this method. This happens whenever I extend the sentry user model. (I have updated my configuration as well)

My User model does not have anything except for the fillable and hidden properties. Removing these still gives me the nesting error.

Yes, I have xdebug and have tried increasing the value to 10,000 even. 

The error comes from Laravel's Str.php studly method whenever I call 
```php
Sentry::createUser([ 
    'email' => '',
    'password' => ''
])
```

Any information would be appreciated.

P.S. There is no stacktrace because it starts and stops with the Str.php file

**Comment by brunogaspar** [comment]
Hi, 

Tested on:
- Laravel 4.1.12
- Laravel 4.1.13
- Laravel 4.1.14
- Laravel 4.1.15
- Laravel 4.1.16 (latest version)

With Sentry 2.1.4

Tried your snippet with and without a custom model, everything is working as expected, it throws a `Cartalyst\Sentry\Users\LoginRequiredException` exception, which is the expected.

--

Are you able to replicate this on a fresh Laravel installation?

**Comment by jamoy** [comment]
I believe it is a misconfiguration on my distro. Just tried on a fresh install and it seemed fine. Trying to find out what happened.

Thanks @brunogaspar
