### ISSUE TITLE
Specify Database Explicitly

### ISSUE THREAD

**Issue by dud3** [cartalyst/sentry#503]
Is there a way of specifying an explicit database connection to the sentry tables.
The reason for this is that, I'm using multiple databases and trying to use the sentry only for authentication and permissions.

My current solution:
```php
class SentryUser extends Cartalyst\Sentry\Users\Eloquent\User {

	protected $connection;

	public function __construct() {
		$this->connection = Config::get('constants.g_center_db_name');
	}

}
```
But in this way I have to specify the connection separately in each sentry model.

Thanks in advice.

**Comment by brunogaspar** [comment]
Not really sure of any better way atm, sorry.
