### ISSUE TITLE
Reference to user_id in ThrottleProvider should be changable

### ISSUE THREAD

**Issue by bertramtruong** [cartalyst/sentry#504]
I'm attempting to rename my 'users' table to 'customers' as that would better align to my business requirements. Upon changing all references of my models to reflect customers (ie. customer_id), I noticed that there is one reference that is unchangeable via the Sentry published configuration file that exists in ThrottleProvider.

The line in question is this:
(Cartalyst/Sentry/Throttling/Eloquent/Provider.php, line 77)

```php
$query = $model->where('user_id', '=', ($userId = $user->getId()));
```

Of course, this should only affect Laravel users as it is used by the Eloquent user model. I propose that user_id is either:

1. Possible to be supplied as part of the published configuration file.
2. Included as new variable/function of the User model.

If this issue is acknowledged and either 1 or 2 is chosen, I'm happy to provide a PR to fix the issue.

**Comment by brunogaspar** [comment]
I guess you can just override the Throttle provider for your use case.
