### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by alairock** [cartalyst/sentry#505]
I need support for Laravel 5. Are there shortcuts to getting the existing package to work, or do I need to wait for a release. 

I can't go much longer, before I will have to find an alternative to Sentry.

**Comment by suwardany** [comment]
Checkout the `feature/laravel-5` branch

**Comment by alairock** [comment]
I saw that, but is it stable enough to work from?

**Comment by suwardany** [comment]
It's only the service provider changed, whether or not you want to use that before a tag is released is really up to you.

I don't have any eta atm for the release date, but most likely within the coming week.
