### ISSUE TITLE
Sentry for Laravel 5

### ISSUE THREAD

**Issue by vincentschroeder** [cartalyst/sentry#510]
Will Sentry work with the latest version of Laravel 5?

**Comment by suwardany** [comment]
check the feature/laravel-5 branch



On February 13, 2015 at 5:31:49 PM GMT+2, Vincent Schröder <notifications@github.com> wrote:Will Sentry work with the latest version of Laravel 5?  —Reply to this email directly or view it on GitHub.

**Comment by fragale** [comment]
Hi, 
the branch feature/laravel-5 is ready to go?
is stable to use in Laravel 5?

Thanks.

**Comment by brunogaspar** [comment]
@fragale As far as i know yes, you can use that branch until we merge to master and tag Sentry 3.0.

We don't have any ETA on when that's going to happen though.

**Comment by fragale** [comment]
@brunogaspar Thanks, I will use this branch then.
I eagerly await the version 3
Do you plan to comunicate this to us when this happens?

**Comment by brunogaspar** [comment]
@fragale You can keep an eye on this list https://medium.com/cartalyst-development/laravel-5-support-4c11e01c3337 and on our [Twitter](https://twitter.com/Cartalyst).

**Comment by mistakevin** [comment]
The medium.com article says sentry only has a laravel-5 branch with a side note of "Some packages may have had their laravel-5 branches merged to master in preparation for release." Twitter says "All packages updated to #laravel5". I don't see any merges or commits on master that shows that the branch has been merged in. Any official statement on current/upcoming status?

**Comment by brunogaspar** [comment]
@mistakevin On the tweet we don't say we have relased stable versions of the packages, but that all the packages were updated to work on Laravel 5, both premium and free packages.

We don't have any ETA on when Sentry will have a stable release for L5.

**Comment by mistakevin** [comment]
Thanks! @brunogaspar
