### ISSUE TITLE
laravel-5 branch, Class request does not exist when calling from phpunit

### ISSUE THREAD

**Issue by briedis** [cartalyst/sentry#511]
When calling `Sentry::register(..)` from phpunit, I get this error:
```
ReflectionException: Class request does not exist

[..]Illuminate\Container\Container.php:776
[..]Illuminate\Container\Container.php:656
[..]Illuminate\Foundation\Application.php:572
[..]Illuminate\Container\Container.php:1231
[..]Cartalyst\Sentry\SentryServiceProvider.php:289
[..]Illuminate\Container\Container.php:290
[..]Illuminate\Container\Container.php:773
[..]Illuminate\Container\Container.php:656
[..]Illuminate\Foundation\Application.php:572
[..]Illuminate\Container\Container.php:1231
[..]Cartalyst\Sentry\SentryServiceProvider.php:308
[..]Illuminate\Container\Container.php:290
[..]Illuminate\Container\Container.php:773
[..]Illuminate\Container\Container.php:656
[..]Illuminate\Foundation\Application.php:572
[..]Illuminate\Container\Container.php:1231
[..]Illuminate\Support\Facades\Facade.php:148
[..]Illuminate\Support\Facades\Facade.php:118
[..]Illuminate\Support\Facades\Facade.php:202
```

Cache and Session drivers are set to arrays.

Installed sentry version in composer:
`"cartalyst/sentry": "dev-feature/laravel-5#78c4dd21d1ddd41c2b2c54301b9e5771e1e42bf4",`

In "local" environment everything works fine. Only tests fail.

**Comment by brunogaspar** [comment]
Hello @briedis 

I don't believe the tests were updated (didn't check to be honest) to Laravel 5 as of yet.

If you want to help on updating them, go ahead, it's Open Source anyways, otherwise these we'll need to wait until we have some spare time to work on Sentry to tag a stable release for Laravel 5.

**Comment by briedis** [comment]
I think I know what's going on.

Normally, there is an 'request' instance availablo for the app, but in testing environment, no request instance is created because, well, there is no request :)

I just don't know how to fix this. Detect testing environment in the service provider and pass a custom request insance?

**Comment by briedis** [comment]
I submitted a pull request with a potential fix. Please review :)

**Comment by suwardany** [comment]
Hello @briedis, i'm unable to reproduce any exceptions that are thrown due to the request class being not found.

Could you provide us with more details on how to reproduce that?

**Comment by briedis** [comment]
I'm really ashamed because turns out there was a mistake in my code.
Somehow, in my TestCase base class I bootstrapped this:
```
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();
```

Instead of this:
```
$app->make(\Illuminate\Contracts\Http\Kernel::class)->bootstrap();
```

Aaaahhh, all those wasted hours :@
