### ISSUE TITLE
using illuminate/database 4.2 or newer

### ISSUE THREAD

**Issue by eman1986** [cartalyst/sentry#517]
forgive me if this isn't the correct place to ask this, but I'm looking to use illuminate/database 4.2 or possibly 5.0 on a project I'm working on but according to your composer file sentry doesn't support 4.2 or newer. Does that mean I'll have to have two instances of illuminate/database installed?

Thanks

**Comment by suwardany** [comment]
It does support 4.2, those constraints are dev-dependencies that do not affect the version you require.
