### ISSUE TITLE
Laravel 5 - Artisan Migration

### ISSUE THREAD

**Issue by tafarifilho** [cartalyst/sentry#518]
The Laravel 5 dont have the "--package" migrate option in artisan.
The file /schema/mysql.sql will not be recognized by the option "--path", because it is in sql format.
The file must be changed to Laravel 5 Schema Builder.

**Comment by brunogaspar** [comment]
Just use the `feature/laravel-5` branch and run the `php artisan vendor:publish` to publish the migration then run `php artisan migrate`.

**Comment by shehi** [comment]
Although I have added Sentry to my composer.json and already updated and fetched the code (dev-feature/laravel-5), when I run ```php artisan vendor:publish``` it only copies ```_ide_helper.php``` file that belongs to a different package I am using - no mention of any Sentry assets. Also, as you mention in #522 , ```php artisan config:publish cartalyst/sentry``` doesn't really work - there is no ```config:publish``` command in Artisan in Laravel 5 and ```vendor:publish``` doesn't accept any parameters as well.

In nutshell, can we please have a documentation for Laravel 5 version of Sentry please?

**Comment by shehi** [comment]
Ok, after adding Provider class to the list of providers in ```conf/app.php``` it picked up the assets. Moving on... :)
