### ISSUE TITLE
Laravel 5 - Vendor publish

### ISSUE THREAD

**Issue by ChristianGiupponi** [cartalyst/sentry#519]
On a new installation of Laravel5 I have added this to my composer.json:

~~~
 "cartalyst/sentry": "dev-master"
~~~

Then:

~~~
composer install
~~~

Then:

~~~
php artisan vendor:publish
~~~

But I get:

~~~
 [BadMethodCallException]            
  Call to undefined method [package] 
~~~

**Comment by suwardany** [comment]
Check https://github.com/cartalyst/sentry/issues/518#issuecomment-78109233

**Comment by ChristianGiupponi** [comment]
That's what I have done, maybe the "dev-master" do not refers to that branch?

**Comment by suwardany** [comment]
`dev-feature/laravel-5`
