### ISSUE TITLE
Laravel 5 - Publish method should be inside the boot() method

### ISSUE THREAD

**Issue by ghunti** [cartalyst/sentry#521]
Looking at the Laravel 5 feature branch, it seems that the call to $this->publishes() should be placed inside the boot() method on the service provider (according to the documentation).
I'm I missing something?

Thanks

**Comment by brunogaspar** [comment]
We keep it on the `register` because we're using the `mergeConfigFrom` this way we don't repeat stuff.

It works nevertheless.

**Comment by ghunti** [comment]
Hi @brunogaspar .
Thanks for the quick answer. I'm still looking through the documentation, and learning L5
With ```mergeConfigFrom``` where should the configuration end up so the users can override it? Do I need to run any artisan commands?

Thanks
