### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by oleynikd** [cartalyst/sentry#522]
As long as could not find answers on your site, readme.md and there's no Wiki, I have no other optinon then asking questions here. Sorry.

#### 1
What is the difference between `Sentry::register()` and `Sentry::createUser()` ?

#### 2
What is a Throttling Feature ?

Thanks.

**Comment by brunogaspar** [comment]
Hello @oleynikd ,

**1**

`createUser` Just creates the user and activation must be done "manually".

https://cartalyst.com/manual/sentry/2.1#sentry::createuser()

`register` Does the same as `createUser` however if you pass a boolean of `true` as the second argument, the user get's activated.

https://cartalyst.com/manual/sentry/2.1#sentry::register()

**2**

Throttling is a "measure" to prevent multiple login attempts of a given user.

Hope it answers your questions.

Regards.

**Comment by oleynikd** [comment]
Than you @brunogaspar 
I want to extend default functionality (add couple fields to users table) maybe there is some kind of extended tutorial for this somewhere? Thanks.

**Comment by brunogaspar** [comment]
@oleynikd 

I believe you can just add those extra fields to your table and just pass them on the array when registering the user.

But if you get a mass assignment exception, ou'll need to most likely add those extra fields to the `$fillable` property on the User model, and to do that, you'll need to create a User model that extends the base Sentry User model, here's the steps to do it:

#### 1

You need to publish the Sentry configuration file, run `php artisan config:publish cartalyst/sentry`

#### 2

Create your User model and save it somewhere on your application, like on `app/models` directory:

```php
use Cartalyst\Sentry\Users\Eloquent\User as SentryUserModel;

class User extends SentryUserModel {

}
```

#### 3

Now you need to update the `$fillable` property on your model and add those fields:

```php
use Cartalyst\Sentry\Users\Eloquent\User as SentryUserModel;

class User extends SentryUserModel {

	protected $fillable = [
		'your_field', 'another_field_here', 'yet_another_field',
	];

}
```

#### 4

Open the file `app/config/packages/cartalyst/sentry/config.php` and change the line [#123](https://github.com/cartalyst/sentry/blob/2.1/src/config/config.php#L123) to something like 'User'.

> **Note:** If your model is namespaced, please use the FQCN.

--

Let me know if you have any issues.

**Comment by oleynikd** [comment]
Thank you a lot!!! Wow. All seems to be clear except `#1`. Is it something from Laravel framework, right? But I'm not using any framework....

**Comment by brunogaspar** [comment]
Ah sorry, i assumed you were using Laravel.

In that case you'll need to do something like this

```php
$model = 'User';

Sentry::getUserProvider()->setModel($model);
```

**Comment by oleynikd** [comment]
Thank you for your help!!!

**Comment by oleynikd** [comment]
Sorry for bothering you, but I need an advice to be sure Sentry fits before I went too far...

I'm building API for my mobile application. First step is to create auth system for registering / authenticating my users. 

My clients will be mobile Apps (iOS, Android...) not web-browsers, so "cookies" don't make any sense, right..? I thought about creating some type of semi-static auth token that will be generated after login and saved on client's side for some period of time to be able to auth (recognise) user with it at next request. Main reason for this is that I don't want to add login/pass to each requests from client to server (mainly due to security reasons)...

Next step will be creating the API structure that will also use DB a lot saving and reading tons of data from it...

As I can see for now - Sentry is nice base to start from... Am I right?

Thank you once again.

**Comment by shehi** [comment]
Hi @brunogaspar , 

I have a question regarding Laravel 5 support for Sentry: Is it completely ported for Laravel 5 compatibility? I noticed master branch doesn't have Laravel 5, only v. 4. I want to use the package in my open source software and extend over it if possible. Please be kind enough to enlighten me in this regard.
