### ISSUE TITLE
Laravel 5 - Sentry::login return null

### ISSUE THREAD

**Issue by ChristianGiupponi** [cartalyst/sentry#526]
If I try to check the result of the login it returns null, is it normal?

~~~
$user = \Sentry::findUserByCredentials( [
       'email'    => $credentials['email'],
       'password' => $credentials['password'],
]);
        
$esito = \Sentry::login( $user, $credentials['remember'] );
~~~

**Comment by brunogaspar** [comment]
The `login` method returns nothing https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/Sentry.php#L313

You need to use `Sentry::getUser()` instead.
