### ISSUE TITLE
users_groups relationship cascade on parent delete

### ISSUE THREAD

**Issue by conradhappeliv** [cartalyst/sentry#527]
Right now, it seems that even if a user or group has been deleted from the database, the relationship still remains in the `users_groups` table. Now, correct me if I'm wrong, but should the rows in which a user a group no longer exists be deleted as well?

What I'm suggesting is adding an `ON DELETE CASCADE` constraint to this table.

**Comment by brunogaspar** [comment]
Hello,

I've tried this on my end and the `detach` calls seems to be called properly here, as on my end the entries are being removed correctly either if i delete a group or an user.

Relevant code:
- [Delete group deletes the users relations](https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/Groups/Eloquent/Group.php#L280)
- [Delete user deletes groups relations](https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/Users/Eloquent/User.php#L327)

If this is not deleting your users or groups relations on your end, then something is wrong there. 
Please try to debug and see where it fails.

Your proposed fix was already [proposed before](https://github.com/cartalyst/sentry/pull/106) and was declined.

**Comment by conradhappeliv** [comment]
It does work when deleting users or groups through Sentry, but I had deleted a few users manually through MySQL and expected their corresponding rows in the relation table to be deleted and they weren't. 

It's not essential to the operation of Sentry as most people may never even delete from the database manually, but I don't think it would add too much complexity. 

#106 is pretty much what I was proposing.

**Comment by brunogaspar** [comment]
Right, but as suggested on #106, you can create your own migration(s) and add the foreign keys through there.
