### ISSUE TITLE
Issue while adding it to config.php in Codigniter

### ISSUE THREAD

**Issue by samarulrajt** [cartalyst/sentry#528]
Codigniter shows the following error
A PHP Error was encountered

Severity: Warning

Message: Class 'Cartalyst\Sentry\Facades\CI\Sentry' not found

Filename: config/config.php

while adding in application /config/config.php
class_alias('Cartalyst\Sentry\Facades\CI\Sentry', 'Sentry');

**Comment by brunogaspar** [comment]
Which version of CodeIgniter?

**Comment by samarulrajt** [comment]
https://github.com/bcit-ci/CodeIgniter/archive/3.0.0.zip

**Comment by brunogaspar** [comment]
That version of CodeIgniter doesn't come with a `composer.json` therefore the Composer autoload file is not being required which is expected.

Either download the `dev` version of CodeIgniter 3 which already seems to handle [this](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/CodeIgniter.php#L160-L181) or follow a [tutorial](https://philsturgeon.uk/blog/2012/05/composer-with-codeigniter/) that will help you to integrate Composer on CodeIgniter, as you'll need to require the Composer autoload file.
