### ISSUE TITLE
How to allowing more then one user to be logged in at the same time?

### ISSUE THREAD

**Issue by lhyaax** [cartalyst/sentry#529]
Hi,
I use laravel,I want know how to allowing more then one user to be logged in at the same time?
thx.

**Comment by drsii** [comment]
This is not possible with sentry. Consider upgrading to Sentinel which supports multiple persistences.

https://cartalyst.com/manual/sentinel/2.0#sentry-vs-sentinel

**Comment by MangoMM** [comment]
See a solution on S/O http://stackoverflow.com/a/23394423/1239122
