### ISSUE TITLE
Allow user login from any ip address

### ISSUE THREAD

**Issue by jpilldev** [cartalyst/sentry#532]
Hello.

i'm using Sentry in Laravel 4.2, i noticed that the an user can access just from the ip of the first login, that is stored y throttle table; so, i need that the users can login from any network IP, ¿how can i allow that without change directly in the database.

Thanks.

**Comment by brunogaspar** [comment]
I don't believe Sentry prevents you from logging in from different ip addresses, however, if you log in from ip A and then you log in from ip B, ip A access will be revoked, is that what you mean?

**Comment by jpilldev** [comment]
I see.
So, the IP in the table is not updated when an user try to login, the access are just denied.

Thanks.

**Comment by brunogaspar** [comment]
Correct, Sentry doesn't have the concept of persistencies (having sessions from other devices for example).
