### ISSUE TITLE
Installation process in laravel 5

### ISSUE THREAD

**Issue by ulshamim** [cartalyst/sentry#533]
Hello, 
Can any one tell me the process to install sentry in laravel 5? I used "cartalyst/sentry": "2.1.*" in composer.json but it didn't work.

**Comment by brunogaspar** [comment]
You need to use the `feature/laravel-5` branch.

> **Note**: You probably need to delete the default Laravel migrations before running the last step, as they might create a "conflict" since Laravel comes with a migration that creates a users table, but Sentry creates it too.

__Didn't tested the steps and something might be missing, but it should help.__

- Add the `"cartalyst/sentry": "dev-feature/laravel-5@dev"` to your `composer.json` file and run `composer update`.
- Add the Sentry Service Provider 'Cartalyst\Sentry\SentryServiceProvider' to the `providers` list on your `config/app.php` file. 
- Add the Sentry Facade alias `'Sentry' => 'Cartalyst\Sentry\Facades\Laravel\Sentry'` to the `aliases` list on your `config/app.php` file. 
- Run `php artisan vendor:publish` and then `php artisan migrate`.

**Comment by ulshamim** [comment]
Is this command needed? php artisan config:publish cartalyst/sentry

**Comment by brunogaspar** [comment]
There's no `config:publish` on Laravel 5, you need to use the "replacement", `vendor:publish` command, which will publish both the config file and the migrations into your app.

**Comment by ulshamim** [comment]
ok thanks a lot
