### ISSUE TITLE
Clear session for arbitrary user

### ISSUE THREAD

**Issue by keith-g** [cartalyst/sentry#534]
I'm trying to implement a way for admins on my site to log out any user (eg. if the user lost their device).

How would I be able to achieve this? I tried looking for ways to clear the session for an arbitrary user, but couldn't really find any reliable info.

**Comment by drsii** [comment]
You would need to clear the persist_code in the users table. This will effectively log any active users out.

**Comment by keith-g** [comment]
Awesome! Thanks.
