### ISSUE TITLE
Register an user with the same email already registered

### ISSUE THREAD

**Issue by SoldierCorp** [cartalyst/sentry#537]
Hi!

I'm using Laravel 4.2 and Sentry 2.1 but I want to know if you have a parameter to register a new user with an email which is already registered.

Thanks!

**Comment by brunogaspar** [comment]
You'll need to change the login identifier on the config file to something else, otherwise how would you identify which email to login?

**Comment by SoldierCorp** [comment]
I want to use the same login identifier for both accounts not to have a different identifier... I already modified in your vendor code in the User class to set when I want to have the login identifier as a unique field to register/login or not.

**Comment by brunogaspar** [comment]
Not sure that i'm following, can you elaborate?
